import requests
from flask import Flask, render_template, request, redirect, session
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.secret_key = "navora_secret_key"

app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///navora.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db = SQLAlchemy(app)

# ================= DATABASE =================

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(200), unique=True)
    password = db.Column(db.String(200))


class Trip(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_email = db.Column(db.String(200))
    destination = db.Column(db.String(200))
    days = db.Column(db.String(50))
    budget = db.Column(db.String(50))
    mood = db.Column(db.String(100))


with app.app_context():
    db.create_all()

# ================= LOGIN =================

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(
            email=email,
            password=password
        ).first()

        if user:
            session["user"] = email
            return redirect("/")

    return render_template("login.html")


# ================= SIGNUP =================

@app.route("/signup", methods=["GET", "POST"])
def signup():

    if request.method == "POST":

        email = request.form.get("email")
        password = request.form.get("password")

        existing = User.query.filter_by(
            email=email
        ).first()

        if existing:
            return redirect("/login")

        user = User(
            email=email,
            password=password
        )

        db.session.add(user)
        db.session.commit()

        return redirect("/login")

    return render_template("signup.html")


# ================= LOGOUT =================

@app.route("/logout")
def logout():

    session.clear()

    return redirect("/login")


# ================= HOME =================

@app.route("/", methods=["GET", "POST"])
def home():

    if "user" not in session:
        return redirect("/login")

    plan = ""
    dna = ""

    destination = ""
    days = ""
    budget = ""
    mood = ""

    hotel_budget = 0
    food_budget = 0
    transport_budget = 0
    activity_budget = 0
    emergency_budget = 0

    city_info = None
    map_url = ""

    if request.method == "POST":

     destination = request.form.get("destination", "")
    days = request.form.get("days", "")
    budget = request.form.get("budget", "0")
    mood = request.form.get("mood", "")

    if mood == "Adventure":
        dna = "🏔 Mountain Explorer"
    elif mood == "Luxury":
        dna = "💎 Luxury Traveller"
    elif mood == "Relax":
        dna = "🌴 Peace Seeker"
    elif mood == "Romantic":
        dna = "🌹 Romantic Wanderer"
    else:
        dna = "🎉 Nightlife Hunter"

    try:
        budget_int = int(budget)
    except ValueError:
        budget_int = 0

    hotel_budget = int(budget_int * 0.45)
    food_budget = int(budget_int * 0.20)
    transport_budget = int(budget_int * 0.15)
    activity_budget = int(budget_int * 0.15)
    emergency_budget = int(budget_int * 0.05)

    plan = f"""
🌍 Destination: {destination}

🎭 Mood: {mood}

🧬 Travel DNA: {dna}

📅 Duration: {days} Days

💰 Budget: ₹{budget}

━━━━━━━━━━━━━━

DAY 1
• Explore top attractions
• Local food experience
• Photography spots

DAY 2
• Hidden gems
• Shopping
• Cultural exploration

━━━━━━━━━━━━━━

✨ Generated by Navora AI
"""

    return render_template(
    "index.html",
    username=session["user"],
    plan=plan,
    destination=destination,
    days=days,
    budget=budget,
    mood=mood,
    dna=dna,
    hotel_budget=hotel_budget,
    food_budget=food_budget,
    transport_budget=transport_budget,
    activity_budget=activity_budget,
    emergency_budget=emergency_budget
)


# ================= SAVE TRIP =================

@app.route("/save_trip", methods=["POST"])
def save_trip():

    if "user" not in session:
        return redirect("/login")

    trip = Trip(
        user_email=session["user"],
        destination=request.form.get("destination"),
        days=request.form.get("days"),
        budget=request.form.get("budget"),
        mood=request.form.get("mood")
    )

    db.session.add(trip)
    db.session.commit()

    return redirect("/my_trips")


# ================= MY TRIPS =================

@app.route("/my_trips")
def my_trips():

    if "user" not in session:
        return redirect("/login")

    trips = Trip.query.filter_by(
        user_email=session["user"]
    ).all()

    return render_template(
        "my_trips.html",
        trips=trips
    )


# ================= DELETE =================

@app.route("/delete/<int:id>")
def delete(id):

    if "user" not in session:
        return redirect("/login")

    trip = Trip.query.get(id)

    if trip:
        db.session.delete(trip)
        db.session.commit()

    return redirect("/my_trips")


# ================= RUN =================

if __name__ == "__main__":
    app.run(debug=True)